# site_name: Eldyn.io Docs
# nav:
#  - Home: index.md
#  - Lore: pages/lore/index.md
#  - API:
#    - Overview: pages/api/index.md
#    - Authentication: pages/api/authentication.md
#    - User: pages/api/user.md
#    - Leaderboard: pages/api/leaderboard.md
